questions = [
    "Show me the trend of sales for the last 6 months",
    "Show me a quarterly trend of sales for the last 4 quarters",
    "Show me a quarterly trend of sales for the last year",
    "Trend of average order value (AOV) for the last 6 months",
    "Monthly trend of average order value (AOV)",
    "Net revenue by state for last month",
    "Which are the top 5 cities by sales in April 2024?",
    "Trend of gross vs. net sales for the last 12 months",
    "Split of average order value (AOV) by new and returning customers",
    "How many new customers did I get in April 2024?",
    "Trend of average order value (AOV) for first-time customers for the last 6 months",
    "Percentage of returns for new customers in April 2024",
    "Trend of return rate in the last 6 months",
    "Which was the day with the highest number of orders in the last month?",
    "Month-over-month (MoM) revenue growth rate for the last 6 months",
    "Weekly trend of revenue in the last quarter",
    "Which week saw the lowest sales in the last 12 months?",
    "Which week saw the lowest average order value (AOV) in the last quarter?",
    "Top 10 bestselling SKUs in April 2024",
    "Top 10 bestselling SKUs on Shopify this year",
    "Top 10 bestselling SKUs in the state with the highest sales this year",
    "Which are the states with the lowest return rate in terms of revenue?",
    "States with the highest returning customer rate",
    "Split of revenue by state in South India",
    "How many orders has my top customer placed?",
    "Bestselling SKUs for new customers vs. returning customers",
    "Lowest selling SKUs on Amazon vs. Shopify",
    "What are the top-performing categories for Q1 2024?",
    "Show the retention rate of customers acquired during the holiday season last year",
    "What percentage of total sales did repeat customers contribute in the last quarter?",
    "What is the average lifetime value of a customer as of 2024?",
    "Which product categories have the highest growth potential based on current trends?",
    "Which geographical regions have shown the most growth in the last year?",
    "What is the month-over-month (MoM) growth rate of sales for the last 12 months?",
    "Show the monthly trend of new customer acquisition for the last year",
    "What is the average order frequency per customer in the last 6 months?",
    "What is the customer lifetime value by channel?",
    "How many repeat purchases were made in Q1 2024?",
    "Compare the return rates for each product category in the last year",
    "Identify the top 5 products with the highest return rates in the last quarter",
    "What is the correlation between product price and return rate?",
    "How many customers used a discount code in April 2024?",
    "Show the trend of discount code usage over the past year",
    "What is the average discount applied per order in the last 6 months?",
    "Compare the sales performance of products before and after a price change",
    "What is the average time between a customer's first and second purchase?",
    "What percentage of total revenue came from international sales in the last year?",
    "Show the monthly trend of sales by product category",
    "What is the average number of items per order for new customers vs. returning customers?",
    "What percentage of orders included a promotional item?",
    "Compare the sales performance during peak hours vs. non-peak hours",
    "What is the average revenue per customer in April 2024?",
    "Identify the top 5 states by highest average order value (AOV) in the last year",
    "Compare the return rates for orders placed on weekdays vs. weekends",
    "Compare the sales growth rates of the top 5 product categories over the past year",
    "What is the percentage of non-metro / non-tier-1 city revenue?",
    "Sales trend for the last 6 months",
    "What are my sales for the last quarter?",
    "Give me the revenue split for the last month by channel",
    "Net revenue for the last 180 days",
    "What is the average order value (AOV) of first-time customers?",
    "Weekly breakdown of gross sales for the current year",
    "What was the AOV for last month?",
    "Show me the trend of sales by source for the last 6 months",
    "How many of my customers have purchased more than once within the last 12 months?",
    "Orders by state for April?",
    "What is the quarterly trend of orders for the last 4 quarters?",
    "Average order value (AOV) trend for Shopify and Amazon in the last 3 months",
    "AOV for the last month on Shopify",
    "Trend of AOV for Shopify in the last 3 months",
    "Which are the states with the lowest return rate in terms of revenue?",
    "Show me the trend of orders from Shopify for this year"
]